"""Создание таблицы products

Revision ID: cf8877fe010a
Revises: 07901c353182
Create Date: 2024-09-05 02:55:50.750524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8877fe010a'
down_revision: Union[str, None] = '07901c353182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('materials', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('filler', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'filler')
    op.drop_column('products', 'materials')
    # ### end Alembic commands ###
